### ISSUE TITLE
Search Implementation And Download folder

### ISSUE THREAD

**Issue by vicone666** [msahakyan/music-player#2]
Wonderful app! 

Can you implement search? Also I have an issue when downloading, it doesnt save to any folder although it does say "downloading" can you implement a folder for those downloads so we can playback the downloads in the same app?

**Comment by msahakyan** [comment]
Hi @vicone666,

Actually the downloading folder has the following path: **/storage/emulated/0/Music**/free_music. You can open it via any `File Manager` app and see already downloaded .mp3 files. What is related to the functionality that users can open downloads and play them inside the app is not implemented yet (but it is in my list). Search API of `Free Music Archive` is probably the worst one I ever saw (there is no specification is search query goes by album title, artist name or song name). I have already implemented search functionality based on that API  (https://freemusicarchive.org/api). It is in `quick-search` branch (you can check it out). There are still some small things remaining, after I will merge it back to the `master` branch.

Best,
Mikayel

**Comment by msahakyan** [comment]
Hi @vicone666,

I merged `quick-search` branch to `master`. 

BR,
Mikayel
